### ISSUE TITLE
Cannot install: cannot find package "github.com/hashicorp/consul/consul/structs"

### ISSUE THREAD

**Issue by belonesox** [outbrain/consul-raftdb-reader#1]
Cannot install: 

```
 $ go get -u github.com/outbrain/consul-raftdb-reader
package github.com/hashicorp/consul/consul/structs: cannot find package "github.com/hashicorp/consul/consul/structs" in any of:
	/usr/lib64/golang/src/github.com/hashicorp/consul/consul/structs (from $GOROOT)
	/home/stas/go/src/github.com/hashicorp/consul/consul/structs (from $GOPATH)
```

Looks like github.com/hashicorp/consul/consul/structs is gone somewhere

**Comment by jianhaiqing** [comment]
I encounter the same issue. hope the contributor can fix the issue. Many thanks

**Comment by johnjimmyc** [comment]
I had the same issue but I got around it by adding the contents of the structs directory manually..
Download the zip file here
https://github.com/hashicorp/consul

Copy the contents of "consul-master.zip\consul-master\agent\structs" to your go path as specified in the error above

/home/stas/go/src/github.com/hashicorp/consul/consul/structs (from $GOPATH)

then cd into your consul-raftdb-reader directory

cd /root/go/src/github.com/outbrain/consul-raftdb-reader

then run 
go install

That should do it

**Comment by ssagesob** [comment]
Pull request for this change was rebased and merged to the base branch, Thanks!
